### ISSUE TITLE
meta: Few basic commands

### ISSUE THREAD

**Issue by g-anupam** [psh-shell/psh#10]
From the given below list each of you have to implement one built in function and test one external function : 
Built in : 
- cd
- pwd
- echo
- export
- history
External Command to be tested : 
- ls
- mv
- rm
- find
- cp

While testing you have to check all possible uses cases of that function. You may not have to necessarily change the code for testing, but whenever you are pushing your change, Please give a description of what you found out while testing. 

You are allowed to discuss among yourselves and decide who takes which function. 

Constraints : 
- Each person must have one built in function and one external function
- Each person must create a branch and push the changes

As soon as a Pull request is made and merged a message will be put in the group. At that time all other members will have to pull the branch to ensure that you are code is updated with all changes. Do feel free to ask us how to pull ur branch. Good luck Coding!

**Comment by g-anupam** [comment]
One error i just found while testing is , 'cd ..' does not work. Like this test and see for all external functions

**Comment by tejas-techstack** [comment]
just drop whatever is covered already right?
like i know exit is done, cd is done, pwd is done (apart from symlinks support i assume but thats a bit more so its fine)
also i hope the external commands have been tested

**Comment by polarhive** [comment]
> i know exit is done, cd is done, pwd is done (apart from symlinks support i assume but thats a bit more so its fine) also i hope the external commands have been tested

We will close this main issue and create new sub-issues for each feature or command. These sub-issues will remain open until they are thoroughly unit tested.

**Comment by tejas-techstack** [comment]
yea i was thinking about that its a better idea
while creating the sub issues chuck the external commands thing that seems to be a one and done
we dont have to worry to much about them right now

**Comment by polarhive** [comment]
Closing this thread as it appears to be a duplicate. 

We'll focus on addressing specific sub-issues mentioned in thread #13
