### ISSUE TITLE
Exit not exiting with provided status code

### ISSUE THREAD

**Issue by NavneetNayak** [psh-shell/psh#14]
<img width="1127" alt="Screenshot 2024-07-05 at 8 10 50 PM" src="https://github.com/psh-shell/psh/assets/54245165/de970d47-e11c-49d2-b9bd-f985b6e73bff">
The program doesn't exit with the status code provided, in this case 90. Instead it defaults to 0 no matter what exit code you provide

**Comment by adityatr64** [comment]
freeing inputline causes this ,will fix that next commit with the new line error
