### ISSUE TITLE
Run external commands/programs on the system 

### ISSUE THREAD

**Issue by polarhive** [psh-shell/psh#2]
Say, a user types `ls` assume it's an external command and execute the matching program found at `/bin/ls`

The shell should be capable of returning the output of `ls` to STDOUT

---
prerequisite: #1

**Comment by g-anupam** [comment]
Just testing

**Comment by g-anupam** [comment]
I am closing this issue as ls has been moved to one of the commands the mentees have to test in the new updated issue.

**Comment by g-anupam** [comment]
I am closing this issue as ls has been moved to one of the commands the mentees have to test in the new updated issue.
