### ISSUE TITLE
chore/ci: automate testing

### ISSUE THREAD

**Issue by polarhive** [psh-shell/psh#21]
Automate the process of checking if the output of our shell matches zsh's output using unit tests.

TODO:

- [ ] Writing and structuring unit tests
- [ ] Prioritizing commands for testing
- [ ] CI/CD pipeline integration

**Comment by tejas-techstack** [comment]
i guess its better mentors do this part @g-anupam @NavneetNayak

**Comment by tejas-techstack** [comment]
any progress on this?

**Comment by polarhive** [comment]
prereq: #41

**Comment by tejas-techstack** [comment]
chuck this we will see end of next week what happens im closing the issue
