### ISSUE TITLE
bug: symlinks

### ISSUE THREAD

**Issue by tejas-techstack** [psh-shell/psh#23]
Cd now functions properly except when symlinks are used the cd ends up inside the linked dir and can't go back into parent/dir with the symlink using cd ..

**Comment by NavneetNayak** [comment]
<img width="1433" alt="Screenshot 2024-07-06 at 9 31 46 PM" src="https://github.com/psh-shell/psh/assets/54245165/f55ba5d8-a41b-40ce-ae5b-51dd1ae27772">
Same symlink issue is seen with pwd command as well.
