### ISSUE TITLE
The variable quote not initialized might cause issues

### ISSUE THREAD

**Issue by adityatr64** [psh-shell/psh#62]
![Screenshot_20240718_161407](https://github.com/user-attachments/assets/6471faf5-cd52-4805-b218-735a5cddd22a)
![Screenshot_20240718_161416](https://github.com/user-attachments/assets/023116b8-587c-4cc8-bf26-b0a3d43a45f6)
idk what i should change it to,so i didnt touch it

**Comment by tejas-techstack** [comment]
wont cause issues just one error in valgrind but its been fixed
with commit [2c166f6](https://github.com/psh-shell/psh/commit/2c166f6df05f3e9f47e886f9c4f3be40ebeb0880)
