### ISSUE TITLE
feat/qol: man page when cmds have missing arguments or typos

### ISSUE THREAD

**Issue by polarhive** [psh-shell/psh#79]
Promp the user to open the man page, with the command that has a mismatched # no arg to help them understand what went wrong.

**Comment by polarhive** [comment]
run an invalid cmd: then run `echo 0?` and lookout for the previous error code

**Comment by ninsid711** [comment]
> run an invalid cmd: then run `echo 0?` and lookout for the previous error code

isn't it `echo $?` ?

**Comment by ninsid711** [comment]
made a pr for the respective issue.
